### ISSUE TITLE
Update latest release on GitHub

### ISSUE THREAD

**Issue by acabal** [tmmdata/chartist-plugin-tooltip#101]
Currently the latest release on GitHub is 0.0.12, which is quite old.  I spent a long time trying to figure out why the options in the documentation weren't working, before I realized that the current release is actually 0.0.17.

**Comment by dasanra** [comment]
Do you mean latest release in NPM? Be aware that in NPM package has an S at the end, so this is the correct link:
https://www.npmjs.com/package/chartist-plugin-tooltips

**Comment by acabal** [comment]
I mean on GitHub: https://github.com/Globegitter/chartist-plugin-tooltip/releases

v0.0.12 is tagged as "latest release", but it's not.  You have to click the little "show newer tags" button at the top to show the _actual_ latest release.

**Comment by dirak** [comment]
This has been updated. Thanks!
