### ISSUE TITLE
ES6 import fails as function name mismatch on `Chartist.plugins.tooltip`

### ISSUE THREAD

**Issue by a5hik** [tmmdata/chartist-plugin-tooltip#103]
The return and declared functions name are mismatching.. Es6 imports fails because of that. Change it to the same name in both places.

Declared as:
`Chartist.plugins.tooltip`
Returns:
`return Chartist.plugins.tooltips;`

**Comment by dirak** [comment]
This has been fixed c476a2dd255134241e4238f562ac3cb8b617bc79
