### ISSUE TITLE
Tooltip Position is Off

### ISSUE THREAD

**Issue by purplelady105** [tmmdata/chartist-plugin-tooltip#109]
The tooltips are loading on my chart, however they are too high. I am using this with a stacked bar chart. Is there any way to customize the tooltip position(s)? Here is a screenshot of my chart.

![image](https://cloud.githubusercontent.com/assets/28715727/26077003/82b7feb2-396f-11e7-9ecf-1e075ea1c3f7.png)

**Comment by luopio** [comment]
Had the same issue. You'll need to add `position: relative` to your graph element.

**Comment by purplelady105** [comment]
That worked! Thank you!

**Comment by GabrielSiq** [comment]
Had the same issue, it really helped!

**Comment by stdedos** [comment]
Duplicate of #134, #151
