### ISSUE TITLE
Chartist Tooltip not showing if showPoint is set to false

### ISSUE THREAD

**Issue by darklightblue** [tmmdata/chartist-plugin-tooltip#114]
Hello, 

This is my first time using this plugin and it seems that the tooltip is not showing when having this option:

```
        }
            showArea: true,
            showPoint: false, // Don't draw the line chart points
            lineSmooth: false, // Disable line smoothing
            fullWidth: true,
            axisX: {
                showGrid: false,  // We can disable the grid for this axis
            },
            axisY: {
                onlyInteger: true, // Can be set to true or false. If set to true, the scale will be generated with whole numbers only.
            },
            plugins: [
                Chartist.plugins.tooltip()
            ]
        }
```

I tried removing `showPoint` and the tooltip became visible

**Comment by darklightblue** [comment]
I was able to bypass it by setting the `showPoint` to true, and overlap the default style of chartist point to:

```
    .ct-series-a .ct-point {
        stroke: transparent;
    }
```

**Comment by the3rdc** [comment]
Glad you found a work-around. Not showing a tool-tip when there is no point seems correct and intentional, so I'm going to go ahead and close this issue. Please feel free to comment if you disagree.
