### ISSUE TITLE
Live demo is not working

### ISSUE THREAD

**Issue by altinselimi** [tmmdata/chartist-plugin-tooltip#115]
The [link](https://jsfiddle.net/AlexanderKozhevin/aapycL87/) to the live demo provided in readme is not working.

**Comment by dschu-lab** [comment]
I get the same result when trying to use this plugin. The div always renders empty.

**Comment by dirak** [comment]
commit a0eab75 seems to have the fix you are suggesting. That fix is in the latest release of v0.0.18

I do not yet have access to the npm distribution of this plugin, so the issue may be that being behind in releases. Can you confirm the latest release (as distributed here) works for your issue?

**Comment by dschu-lab** [comment]
I've added `"chartist-plugin-tooltips": "git+https://github.com/tmmdata/chartist-plugin-tooltip.git#v0.0.18",` to my `package.json` and run `npm install`.

The `package.json` inside `node-modules/chartist-plugin-tooltip` states:
```
    "version": "0.0.18"
```

But I still have this bug (old conditions)

**Comment by dirak** [comment]
a PR and a way to test it being broken, & correct, would be great. This seems to be an issue we need to add to the test suite, since I found problems with it as well.

**Comment by dschu-lab** [comment]
@dirak While forking I've found the problem we're facing here.
The file in the `src` folder got updated with the fix. But inside the `dist` is still the old code.
I think, all that's needed is an updated `dist` for fixing this error

**Comment by dirak** [comment]
Oh, I think that issue was not in the release because I couldn't confirm if it was a webpack issue, or a general issue. Let me get a few more bugs fixed and we'll have another bug release.

**Comment by dschu-lab** [comment]
In this case I'll skip providing a PR since it's already fix. Thanks for your help. :smile::beers:
