### ISSUE TITLE
Tooltip doesn't show

### ISSUE THREAD

**Issue by kaspar-allenbach** [tmmdata/chartist-plugin-tooltip#13]
Hi.

I try to use the tooltip plugin but it doesn't work.

I can see that the plugin fires when I hover over the chart but it doesn't trigger `display: block;` when I hover over a point. Why could this be?

The tooltip div appears to be empty. I copied the chart js code 1:1 from the website.

Edit: I moved up to jQuery 2.0 now an error appears when I hover over a point:

`chartist-plugin-tooltip.js:53 Uncaught ReferenceError: Ember is not defined`

**Comment by optikfluffel** [comment]
@seppentoni which version are you using? [`CHANGELOG.md`](https://github.com/Globegitter/chartist-plugin-tooltip/blob/master/CHANGELOG.md#008) says:

> ### 0.0.8
> * [BUGFIX] Removed Ember reference

**Comment by ealves-pt** [comment]
Any updates here?

**Comment by dirak** [comment]
closing this issue.
