### ISSUE TITLE
On Pie Donut tooltips don't always show

### ISSUE THREAD

**Issue by karlinnolabs** [tmmdata/chartist-plugin-tooltip#137]
Smaller values of tooltips around the sides of a semicircle donut don't seem to pop up any tooltip, this is pretty annoying as it was these particular values I wanted to be shown.

**Comment by karlinnolabs** [comment]
Found an element over the donut, closing this

**Comment by deQuota** [comment]
Could you please mention that element here

**Comment by karlinnolabs** [comment]
it was just an invisible element on the page, not related to chartist.

**Comment by deQuota** [comment]
Yeah, solved the problem. Thank you
