### ISSUE TITLE
bad work on Firefox 57.0.3

### ISSUE THREAD

**Issue by j574144** [tmmdata/chartist-plugin-tooltip#139]
Hi

Could you help me with tooltip position on mouseove, note both cases (chrome and firefox)

Chorme, work fine

![image](https://user-images.githubusercontent.com/30190050/34655156-62e61f8c-f3d3-11e7-832a-40308133ae3b.png)

Firefox, work bad

![image](https://user-images.githubusercontent.com/30190050/34655163-7e33bbdc-f3d3-11e7-9071-fa55f42c3cd1.png)

Thanks.

**Comment by itelmenko** [comment]
@j574144 Are you sure you are not using an another package?
https://github.com/CodeYellowBV/chartist-plugin-tooltip
That package has this problem.
Please, attach your package.json

**Comment by j574144** [comment]
@itelmenko I'm using this package: 

"chartist-plugin-tooltip": "0.0.11",

I have installed via npm.

Thanks.

**Comment by KristopherRobin1** [comment]
@j574144 For current package you need
```
npm i chartist-plugin-tooltips
```
Letter "s" in the end (chartist-plugin-tooltip**s** instead of chartist-plugin-tooltip).

**Comment by itelmenko** [comment]
@j574144 For current package you need
```
npm i chartist-plugin-tooltips
```
Letter "s" in the end (chartist-plugin-tooltip**s** instead of chartist-plugin-tooltip).

**Comment by j574144** [comment]
@itelmenko thanks for your help

I'm using this from Vue and this not work properly. I choose other option to charts.
