### ISSUE TITLE
is jquery a dependency?

### ISSUE THREAD

**Issue by seabass223** [tmmdata/chartist-plugin-tooltip#155]
ERROR in ./node_modules/chartist-plugin-tooltip/chartist-plugin-tooltip.js
Module not found: Error: Can't resolve 'jquery' in 'node_modules\chartist-plugin-tooltip'

**Comment by seabass223** [comment]
yes

**Comment by arambert** [comment]
for future readers: 'chartist-plugin-tooltip' package on NPM has a jqQery dependency whereas NPM package 'chartist-plugin-tooltips' (with an s) does not...

**Comment by jashsayani** [comment]
Thanks @arambert
