### ISSUE TITLE
Plugin not working in line chart

### ISSUE THREAD

**Issue by juliorosseti** [tmmdata/chartist-plugin-tooltip#165]
Why tooltip not working in line chart? I basically used the github example...

Source code:
https://jsfiddle.net/worf378h/

**Comment by gtato** [comment]
Check the last comment on the issue 127. That worked for me.

https://github.com/tmmdata/chartist-plugin-tooltip/issues/127

**Comment by juliorosseti** [comment]
tks @gtato!
