### ISSUE TITLE
Doesn't work when { donutSolid: true } on a donut chart.

### ISSUE THREAD

**Issue by mtskf** [tmmdata/chartist-plugin-tooltip#175]
I've found the tooltip doesn't show up when a donutSolid option is set true.
It works properly only when donutSolid is turned off.

ie:
```
const chartOptions = {
    chartPadding: 0,
    donut: true,
    donutWidth: 8,
    donutSolid: true,
    fullWidth: true,
    plugins: [
        Chartist.plugins.tooltip()
    ]
 }
```

**Comment by petervtzand** [comment]
I had the same problem. It looks like they already fixed this in this [commit](https://github.com/tmmdata/chartist-plugin-tooltip/commit/dec622fcdd78b542c6efdb4d4b9588bf54c58434). But these changes are not 'pushed' to npm. 

I also found this [repo](https://github.com/LukBukkit/chartist-plugin-tooltip) that's look better maintained but doesn't have these changes for donutSolid yet. So I created a [PR for that](https://github.com/LukBukkit/chartist-plugin-tooltip/pull/4. So I hope they will merge these changes soon and push it to NPM. For now I will use my own fork, so I don't have to wait, I'd suggest you do the same. You can find my changes [here](https://github.com/petervtzand/chartist-plugin-tooltip/commit/0a0fc04bc9f16b3da89cff704f6d979da233bc74)

**Comment by LukBukkit** [comment]
Hello I'm the maintainer of the [fork on NPM](https://www.npmjs.com/package/chartist-plugin-tooltips-updated). 
Thanks to @petervtzand I got to know about the changes and I'll publish them on NPM soon.

**Comment by LukBukkit** [comment]
I've included the pull request into my fork and published the changes on [NPM](https://www.npmjs.com/package/chartist-plugin-tooltips-updated).

**Comment by mtskf** [comment]
@LukBukkit Awesome!!!! Thanks!
