### ISSUE TITLE
NPM Package Confusion

### ISSUE THREAD

**Issue by dandean** [tmmdata/chartist-plugin-tooltip#74]
We just spent a long time trying to debug why the latest version wasn't getting installed until we realized that there's a `chartist-plugin-tooltip` module in NPM, but THIS module uses the plural `chartist-plugin-tooltips`. It's further confusing that the bower version is singular, but the NPM version is plural.

It would be wonderful if the README contained a warning about this.

**Comment by dandean** [comment]
Also, thank you for your work on this module – it is a great help to us.

**Comment by ealves-pt** [comment]
@dandean thank you for your feedback

I think that @Globegitter already contacted the **chartist-plugin-tooltip** NPM owner but don't know the result of that.

I could add the warning though.

**Comment by dirak** [comment]
#113 should be adequate enough to cover this issue. Feel free to re-open @dandean
