### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by tiesont** [tmmdata/chartist-plugin-tooltip#98]
I'm currently in the process of pushing [NuGet](https://www.nuget.org) packages for the Chartist library. [I've asked for and received permission](https://github.com/gionkunz/chartist-js/issues/912) from Gion Kunz to publish the main library and his plugins, but I would like your explicit permission to do the same for your plugin.

Thank you!

**Comment by dirak** [comment]
I'm the current maintainer, and see no issue with this. Let me know if you need any assistance in the future. @tiesont

**Comment by tiesont** [comment]
Thank you! Plugin package has been published to https://www.nuget.org/packages/ChartistJS.Tooltip/
